### ISSUE TITLE
missing genes

### ISSUE THREAD

**Issue by guangtugao** [agshumate/Liftoff#21]
Hi Alaina,
There are some genes in the reference gff, but I cannot find them in the final gff file, or the unmapped_features.txt file. What is the reason for this? If you still keep the gff dile I sent you before, one of such cases is gene3.
Thanks,
Guangtu

**Comment by agshumate** [comment]
hi yes i did notice this too. it was a bug where genes mapped in the first step that did not meet the minimum seq id for copies (-sc) were being counted as unmapped in the copies step. the unmapped_features.txt file is made before the copies step. this has been fixed in v.1.2.1 and i did not notice any more issues when i tested your gff file.

**Comment by guangtugao** [comment]
> hi yes i did notice this too. it was a bug where genes mapped in the first step that did not meet the minimum seq id for copies (-sc) were being counted as unmapped in the copies step. the unmapped_features.txt file is made before the copies step. this has been fixed in v.1.2.1 and i did not notice any more issues when i tested your gff file.

Well, I'm sorry I still cannot find some genes with v1.2.1. The number is just not right. For example, gene3 is in the file NC_035077.1_genes.fa in the temp folder, and I can see there is mapping in the sam file NC_035077.1_to_omya01.sam. Then I cannot see it in either the liftoff.gff file or in the file unmapped_features.txt. It seems that something still has to be fixed, right?
Guangtu

**Comment by agshumate** [comment]
hi i see it here in my gff 
CM023219.1  Liftoff gene    500290  504281  .   -   .   ID=gene3;Dbxref=GeneID:110523749;Name=LOC110523749;gbkey=Gene;gene=LOC110523749;gene_biotype=protein_coding;copy_id=gene3_0;coverage=1.0;sequence_ID=0.99341;extra_copy_number=0

**Comment by agshumate** [comment]
can you confirm you are running v1.2.1?

**Comment by guangtugao** [comment]
Yes.

**Comment by guangtugao** [comment]
What's your command line command?

**Comment by guangtugao** [comment]
Sorry, I also saw it. My bad for not finding it.

**Comment by agshumate** [comment]
do the number of genes in the gff file + the unmapped features file add up now?

**Comment by guangtugao** [comment]
I have one gene that is in both the final gff file and the unmapped feature file. This gene is gene48291 and I noted that the copy_id for this gene in the gff file is gene48291_1, not  gene48291_0. Other than that, everything is good to me.
Thanks for making this nice tool!
Guangtu
